name: android_physical_buttons
description: A flutter plugin for listening android physical buttons.
version: 0.1.0
homepage: https://github.com/wings-j/android-physical-buttons

environment:
  sdk: ">=2.17.3 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: cn.wingsj.android_physical_buttons
        pluginClass: AndroidPhysicalButtonsPlugin

